#!/bin/bash

# Setup Production Environment untuk Laravel Cloud Deployment
# Usage: bash scripts/setup-production-env.sh

echo "=================================================="
echo "Divusi SSO - Production Environment Setup"
echo "=================================================="
echo ""

# Check if .env exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists. Backing up to .env.backup"
    cp .env .env.backup
fi

# Copy .env.example to .env
echo "📋 Creating .env from .env.example..."
cp .env.example .env

echo ""
echo "📝 Please configure these values in .env:"
echo ""
echo "1. APP_KEY (run: php artisan key:generate)"
echo "2. APP_URL (e.g., https://sso.divusi.com)"
echo ""
echo "3. Database:"
echo "   - DB_CONNECTION=mysql"
echo "   - DB_HOST=<Laravel Cloud provides>"
echo "   - DB_DATABASE=<auto-generated>"
echo "   - DB_USERNAME=<auto-generated>"
echo "   - DB_PASSWORD=<auto-generated>"
echo ""
echo "4. Firebase (from Firebase Console):"
echo "   - FIREBASE_API_KEY"
echo "   - FIREBASE_AUTH_DOMAIN"
echo "   - FIREBASE_PROJECT_ID"
echo "   - FIREBASE_STORAGE_BUCKET"
echo "   - FIREBASE_MESSAGING_SENDER_ID"
echo "   - FIREBASE_APP_ID"
echo "   - FIREBASE_SERVICE_ACCOUNT_JSON (full JSON content)"
echo ""
echo "5. Mail (optional, for production):"
echo "   - MAIL_MAILER=smtp"
echo "   - MAIL_HOST=<your mail server>"
echo "   - MAIL_PORT=587"
echo "   - MAIL_USERNAME=<email>"
echo "   - MAIL_PASSWORD=<password>"
echo ""
echo "6. Cache & Session:"
echo "   - CACHE_DRIVER=redis"
echo "   - QUEUE_CONNECTION=redis"
echo "   - SESSION_DRIVER=database"
echo ""
echo "✅ Open .env file and add all necessary values"
echo ""
echo "=================================================="
echo "After configuring .env, run:"
echo "  php artisan key:generate"
echo "  php artisan migrate --force"
echo "=================================================="
